# Generated by Django 4.0.1 on 2022-01-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('director', models.CharField(max_length=50, verbose_name='감독')),
                ('main', models.CharField(max_length=100, verbose_name='주연')),
                ('genre', models.CharField(max_length=100, verbose_name='장르')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('star', models.IntegerField(verbose_name='별점')),
                ('time', models.CharField(max_length=50, verbose_name='러닝타임')),
                ('review', models.TextField(verbose_name='내용')),
                ('year',models.CharField(verbose_name="개봉년도",max_length=50)),
            ],
        ),
    ]
