# Generated by Django 4.0.1 on 2022-01-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='.photo/%Y/%m/%d'),
        ),
    ]
