# Generated by Django 4.0.1 on 2022-01-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('로맨스', '로맨스'), ('공포', '공포'), ('코미디', '코미디'), ('판타지', '판타지'), ('SF', 'SF'), ('사극', '사극')], max_length=100, verbose_name='장르'),
        ),
    ]
